### PR TITLE
Rewrite for UEFI support

### PR DESCRIPTION
**Pull request by phil-opp**
This is still in progress, but I decided to open this PR already to have a place to track the remaining issues:

- [x] Ensure that all API items are documented
- [x] Extend test framework for boot information
- [x] Create a FAT disk image with the `.efi` executable
- [x] Test disk images on real hardware
  - [x] BIOS image
  - [x] UEFI image
- [x] Update the Readme
- [x] ~Improve screen log output~ postponed
- [x]  ~https://github.com/rust-osdev/bootimage/issues/68~ postponed
- [x] ~https://github.com/rust-osdev/bootloader/issues/131~ postponed

### CODE REVIEW

**Comment by pitust** [comment]
Creating the efi partition can be done with parted or fdisk, and the mcopy'ied onto the partition. But that's only on linux, i don't think parted is on windows (or macos for that matter). Or it could use https://github.com/rafalh/rust-fatfs (for FAT) and https://gitlab.redox-os.org/redox-os/gpt (for GPT). I will try to get that to work.

**Comment by phil-opp** [comment]
The FAT/GPT image is now created using the `fatfs`/`gpt` crates. Thanks for the suggestions, @pitust!

**Comment by phil-opp** [comment]
Pre-released https://github.com/rust-osdev/bootloader/commit/8c82e685f1afc9f1f0767e2da15cb19537f850fe as `v0.10.0-alpha-01` for testing.

**Comment by phil-opp** [comment]
Published as v0.10.0

**Pull request merged**
