### PR TITLE
Fix Create Disk Image Example

### PR DESCRIPTION
**Pull request by AlexJMohr**
The example code didn't compile. This patch fixes that.

Let me know if it needs any changes, and thanks for making this awesome crate!

### CODE REVIEW

**Review by phil-opp — APPROVED** [review]
Thanks a lot! Looks like I forgot to try this snippet.

One minor nit: I think the `Path::new` call is simple enough to do apply it in the `out_dir`/`kernel` bindings directly instead of introducing new `out_dir_path`/`kernel_path` bindings. I left some suggestions below for this.

**Comment by AlexJMohr** [comment]
@phil-opp I agree, that looks simpler.

**Comment by asensio-project** [comment]
Hello, I think that in the Cargo.toml file you should change ``ovmf_prebuilt`` to ``ovmf-prebuilt`` because the first package doesn't exists in crates.io but the second does.

**Comment by phil-opp** [comment]
> The compiler complains about `temporary value is freed at the end of this statement`

I think we can use `PathBuf` instead of `Path` to take ownership of the string. I pushed https://github.com/rust-osdev/bootloader/pull/300/commits/63284c610bca46b7f021d842e2300570598c3f99 with that change.

> Hello, I think that in the Cargo.toml file you should change `ovmf_prebuilt` to `ovmf-prebuilt` because the first package doesn't exists in crates.io but the second does.

Thanks, done in https://github.com/rust-osdev/bootloader/pull/300/commits/0d24cef05198572efa3eff9dd2cd80561f883a7d.

**Comment by phil-opp** [comment]
Could you try whether the new version works for you? Then we can finally merge this!

**Comment by asensio-project** [comment]
The new version is working very good, thanks!

**Comment by phil-opp** [comment]
Ok great, thanks for testing!

**Pull request merged**
