### PR TITLE
copy more PML4 entries

### LINKED ISSUE #462: Hang after loading first level 4 table on uefi
I tried my os on real hardware for the first time and found that the bootloader is hanging. I tracked the issue down to this [line](https://github.com/rust-osdev/bootloader/blob/fffa7ceb317328ed19bc0ebaa0028be152095a05/uefi/src/main.rs#L336-L339). I'm still a beginner in os development so any help is appreciated.

I am running it on my laptop which is a lenvo legion 7 which has a AMD Ryzen 7 5800H.

### PR DESCRIPTION
**Pull request by Freax13**
If there is more than 512 GiB of memory, we need to copy more than the first PML4 entry to access it. Similarly if the frame buffer is not in the address range covered by the first PML4 entry, we need to copy more entries in order to access it. We also need to mark these PML4 entries as unusable when allocating virtual addresses for the kernel because the bootloader maps some of them into its own address space.

This is a much simpler solution to #462 than #465. The downside is that we mark some of the kernel's virtual address space as unusable when it doesn't technically need to be.

@colepng Could you please also test this PR?

Supersedes #464
Closes #462

### CODE REVIEW

**Review by phil-opp — APPROVED** [review]
Looks good to me, thanks! And sorry again for the long delay!

**Comment by phil-opp** [comment]
> The downside is that we mark some of the kernel's virtual address space as unusable when it doesn't technically need to be.

Just to clarify: Do you mean unusable for the bootloader or unusable in the memory map (i.e. affecting the kernel)?

**Comment by Freax13** [comment]
> Looks good to me, thanks! And sorry again for the long delay!

Thank you for the review!

> > The downside is that we mark some of the kernel's virtual address space as unusable when it doesn't technically need to be.
> 
> Just to clarify: Do you mean unusable for the bootloader or unusable in the memory map (i.e. affecting the kernel)?

We mark it as unusable for dynamic virtual memory space allocations for the kernel i.e. for mappings configured with [`Mapping::Dynamic`](https://docs.rs/bootloader_api/latest/bootloader_api/config/enum.Mapping.html#variant.Dynamic). IIRC mappings with statically configured addresses are not affected because we never do any checks for those.

**Comment by phil-opp** [comment]
Ah right. So when the UEFI firmware puts the framebuffer somewhere into the second PML4 entry, we won't use any address within that PML4 entry for dynamic kernel mappings?

**Comment by Freax13** [comment]
> Ah right. So when the UEFI firmware puts the framebuffer somewhere into the second PML4 entry, we won't use any address within that PML4 entry for dynamic kernel mappings?

Yes, exactly.

**Comment by Freax13** [comment]
> Ok, thanks for clarifying! Personally, I'm fine with this limitation for now. We can then try to make the used-tracking more precise in some future PR.
> 
> I'm also looking into #465 currently. Which of the two approaches do you prefer?

I like how #465 solves this problem without any limitations for the loaded kernel, but I think the code is much uglier/hackier. I agree that losing a pml4 is acceptable for now. I like your idea of making the used tracking more precise, this would allow us to use the less-hacky from this PR code but also minimize wasting virtual address space.

**Comment by phil-opp** [comment]
Ok, then let's proceed with this PR.

I don't mind the indirect memory access in #465, but I agree that the code seems a bit hacky in places (e.g. a separate translation step for each individual byte or the construction of an invalid `&mut` reference).

**Pull request merged**
