### PR TITLE
SSE feature: remove inline assembly + don't set reserved bits

### PR DESCRIPTION
**Pull request by Freax13**
- get rid of inline assembly
- for some reason the previous version also set bits 9 & 10 in Cr0. according to the developer manual bits 5-16 are reserved

### CODE REVIEW

**Comment by phil-opp** [comment]
Thanks a lot for the pull request!

I'm not sure why we currently set bits 9 and 10 in CR0. From a quick look at the manuals, it seems like you're right that these bits are reserved. Maybe this was a copy&paste error? Perhaps @ethindp who added this code knows more?

**Comment by phil-opp** [comment]
Given that this change only affects the SSE feature and nobody objected it, I'm going to merge it. After all, setting bits 9 and 10 seems like an accident to me.

Thanks for the PR, @Freax13!

**Comment by phil-opp** [comment]
Published as version 0.9.1

**Comment by ethindp** [comment]
I'm honestly not sure myself. The OSDev Wiki listed the code I added
to enable SSE -- I didn't write it, though I probably should have (I
need ASM practice :)). Perhaps its worth asking on the OSDev Forum?

On 4/15/20, Philipp Oppermann <notifications@github.com> wrote:
> Published as version 0.9.1
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/rust-osdev/bootloader/pull/105#issuecomment-613858324


-- 
Signed,
Ethin D. Probst

**Comment by phil-opp** [comment]
Thanks for clarifying! I think as long as it still works, setting these bits was likely a copy&paste error.

**Pull request merged**
