### PR TITLE
fix issue #315

### PR DESCRIPTION
**Pull request by JarlEvanson**
This pull request should close https://github.com/rust-osdev/bootloader/issues/315.

### CODE REVIEW

**Comment by phil-opp** [comment]
Thanks a lot for tackling this! I saw that you also opened a PR on the `uefi-rs` repo to implement sorting the memory map: https://github.com/rust-osdev/uefi-rs/pull/662. Given that this PR looks like it's closed to be merged, I wonder if it makes sense to wait for it instead of making our frame allocation more complex. What do you think?

**Comment by JarlEvanson** [comment]
I think that it makes sense to wait, rather than introducing more complexity.

**Comment by phil-opp** [comment]
Ok, thanks!

**Comment by phil-opp** [comment]
I just merged #360 to update the UEFI dependency to v0.20. We should now be able to use the new `sort` function.

**Pull request closed without merging**
