### PR TITLE
Reserve 3 frames for higher half kernels

### PR DESCRIPTION
**Pull request by Andy-Python-Programmer**
This pull request reserves three frames instead of two for higher half kernel support.

Related: #159

### CODE REVIEW

**Comment by phil-opp** [comment]
Thanks for the PR! I'm currently looking into this issue too and I think there might be a better way to solve this. I'll keep you posted.

**Comment by Andy-Python-Programmer** [comment]
All good!

**Comment by Andy-Python-Programmer** [comment]
For reference the limine bootloader subtracts the fixed higher half offset from the elf header section.

<https://github.com/limine-bootloader/limine/blob/f650e4b41bda371dd8d6fd764bc2c77bcbc3f102/stage23/lib/elf.c#L339>

**Comment by Andy-Python-Programmer** [comment]
Closing as of #161

**Comment by phil-opp** [comment]
I opened #161 with an alternative fix.



> For reference the limine bootloader subtracts the fixed higher half offset from the elf header section.

I'm not sure why this is done, maybe because the bootloader is still in 32 bit mode at this point? In our case, we are already in 64 bit mode when doing the mapping, so we can create mappings across the whole virtual address space without problems.

**Pull request closed without merging**
